version: '3.3'

services:
  pg_database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2304"
      POSTGRES_DB: tatu_sf
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./full_data_dump.sql:/docker-entrypoint-initdb.d/02_data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tatu_sf"]
      interval: 5s
      timeout: 5s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  bot:
    image: "bot"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/bot"
    volumes:
      - .:/usr/src/app/bot
    command: python3 -m bot
    restart: always
    depends_on:
      pg_database:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  pgdata: {}
